---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-application
spec:
  destination:
    namespace: 'infrastructure-application'
    server: 'https://kubernetes.default.svc'
  source:
    path: infrastructure-application/
    repoURL: 'https://github.com/simonkrenger/gitops-admin-webinar.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
